version: '3'

volumes:
  postgres_data:
  alembic:

services:
  postgres:
      image: postgres:13
      env_file: .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
      - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  backend:
    build: ./app
    env_file: .env
    environment:
      - PYTHONPATH=/
    restart: always
    volumes:
      - alembic:/app/alembic
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  gateway:
    image: nginx:1.19.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - backend